apiVersion: v1
kind: Service
metadata:
  name: example-app-metrics
  namespace: default
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
    - name: metrics
      port: 8000 # matches Django server port
      targetPort: 8000
