apiVersion: v1
kind: Secret
metadata:
  name: aiops-secrets
type: Opaque
stringData:
  GITLAB_RETRAIN_WEBHOOK: "https://gitlab.com/api/v4/projects/msolonin%2Fmlops-goit-hw/trigger/pipeline?token=${TOKEN}&ref=final-project"
