apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiops-quality-project.fullname" . }}
  labels:
    app: {{ include "aiops-quality-project.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics   # 👈 must match ServiceMonitor
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ include "aiops-quality-project.name" . }}

