apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aiops-quality-project.fullname" . }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ include "aiops-quality-project.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: 15s
