applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: "https://github.com/msolonin/goit-mlops-hw"
      path: charts/django-app
      targetRevision: lesson-fp
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
