apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: monitoring
type: Opaque
stringData:
  MLFLOW_S3_ENDPOINT_URL: "http://minio.mlops.svc.cluster.local:9000"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  BACKEND_STORE_URI: "postgresql://mlflow:mlflow123@postgresql.mlops.svc.cluster.local:5432/mlflow"
