# FastAPI deployment values
replicaCount: 1
image:
  repository: 020236748758.dkr.ecr.us-east-1.amazonaws.com/aiops-quality-project
  tag: latest
service:
  type: ClusterIP
  port: 8000

# Prometheus/Grafana (via kube-prometheus-stack)
kube-prometheus-stack:
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin123
    service:
      type: ClusterIP
      port: 3000
  prometheus:
    prometheusSpec:
      scrapeInterval: 15s
  alertmanager:
    enabled: false

# Loki + Promtail
loki-stack:
  grafana:
    enabled: false # we already have Grafana in kube-prometheus-stack
  loki:
    enabled: true
  promtail:
    enabled: true
